driver_sources:
  - appium:
      enabled: true
      url: "http://localhost:4723"
      capabilities:
        appActivity: "com.google.android.youtube.app.honeycomb.Shell$HomeActivity"
        appPackage: "com.google.android.youtube"
        automationName: "UiAutomator2"
        deviceName: "emulator-5554"
        platformName: "Android"
  - ble_helper:
      enabled: false
      url: null
      capabilities: {}

elements_sources:
  - appium_find_element:
      enabled: true
      url: null
      capabilities: {}
  - appium_page_source:
      enabled: false
      url: null
      capabilities: {}
  - device_screenshot:
      enabled: true
      url: null
      capabilities: {}
  - webcam_screenshot:
      enabled: false
      url: null
      capabilities: {}

text_detection:
  - easyocr:
      enabled: true
      url: null 
      capabilities: {}
  - pytesseract:
      enabled: false
      url: null
      capabilities: {}
  - google_vision:
      enabled: false
      url: null
      capabilities: {}

image_detection:
  - templatematch:
      enabled: true
      url: null  
      capabilities: {}