name: pre-commit

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Pre-Commit
        run: pip install pre-commit

      - name: Determine Changed Files or Full Scan
        id: changed-files
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "Running from workflow_dispatch. Scanning entire repo."
            echo "CHANGED_FILES=$(git ls-files)" >> $GITHUB_ENV
          else
            echo "Running from pull_request. Checking changed files only."
            BASE_BRANCH=${{ github.base_ref }}
            git fetch origin $BASE_BRANCH --depth=1
            CHANGED_FILES=$(git diff --name-only origin/$BASE_BRANCH HEAD)
            echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
          fi

      - name: Run Pre-Commit Hooks
        run: |
          if [ -n "${{ env.CHANGED_FILES }}" ]; then
            echo "Running pre-commit on:"
            echo "${{ env.CHANGED_FILES }}"
            echo "${{ env.CHANGED_FILES }}" | tr ' ' '\n' | xargs pre-commit run --files
          else
            echo "No changed files to check."
          fi
